---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: todobackend-rc
  namespace: develop-helm
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.api: "glob:0.1.*"
    flux.weave.works/tag.front: "glob:0.1.*"
spec:
  releaseName: todobackend-rc
  chart:
    git: ssh://git@github.com/snahelou/demo-gitops-helm
    path: charts/todobackend
  values:
    api:
      image: repo.treescale.com/snahelou22/middleware:0.1.31
      replicas: 1
    front:
      image: repo.treescale.com/snahelou22/frontend:0.1.32
      replicas: 1
