apiVersion: v1
kind: Service
metadata:
  labels:
    run: api
  name: api
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8082
  selector:
    run: api
  type: LoadBalancer
